<?php $current_weather = $this->getCurrentWeather(765876)->getData(); ?>
<h1><?php echo __('Weather') ?></h1>
<table class="table-weather">
    <tbody>
        <tr>
            <th>Temperature</th>
            <td><?php echo $current_weather['temp']; ?> &#8451;
            </td>
        </tr>
        <tr>
            <th>Min</th>
            <td><?php echo $current_weather['temp_min']; ?> &#8451;
            </td>
        </tr>
        <tr>
            <th>Max</th>
            <td><?php echo $current_weather['temp_max']; ?> &#8451;
            </td>
        </tr>
        <tr>
            <th>Wind</th>
            <td>
                <?php echo $current_weather['wind']; ?> m/s
            </td>
        </tr>
        <tr>
            <th>Pressure</th>
            <td><?php echo $current_weather['pressure']; ?> hpa</td>
        </tr>
        <tr>
            <th>Humidity</th>
            <td><?php echo $current_weather['humidity']; ?> %</td>
        </tr>
    </tbody>
</table>